include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: true
    use_super_parameters: true
    parameter_assignments: true
    no_self_assignments: true
    no_wildcard_variable_uses: true
