name: em_docs
description: "DevDF Estate Manager Docs"
publish_to: 'none'
version: 1.0.0+2
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter


  #Language datetime control
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/app-icon-192.webp
    - assets/images/app-icon-512.png
    - assets/images/dark.jpg

